# Generated by Django 5.0.3 on 2024-03-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basket',
            field=models.JSONField(default=dict, verbose_name='корзина'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
